### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by kalahiri** [axlevxa/typowiki#1]
Just installed your template using the extension manager on a fresh Doku Wiki installation. After selecting typowiki in the configuration panel, the whole site locked up: error 500. I had to remove the template from my site to be able to select the default template again.

**Comment by axlevxa** [comment]
Hi,

Uh oh! I'm sorry that your site broke 💔

I just tested installing the template on a fresh installation and it worked OK for me. Can you confirm that you're uploading only the folder called "typowiki" from within the Github directory, not the whole thing? I'll also update the documentation to make that clearer.

**Comment by axlevxa** [comment]
Closing issue since no further reports.
