### ISSUE TITLE
Search field in top row?

### ISSUE THREAD

**Issue by mbreanish** [axlevxa/typowiki#10]
Hello axlevxa, great theme, thank you very much!

Is there an easy way to place the search field in the top row to keep it always visible? 

Thanks, Max

<img width="820" alt="Example" src="https://user-images.githubusercontent.com/32209182/185440519-9fd90a62-3ba6-4fbd-969e-8405e3082d95.png">

**Comment by axlevxa** [comment]
Hi, it is possible but wouldn't be super easy!

Putting a search bar there is simple, just put `<?php tpl_searchform() ?>` wherever you want it to appear in the main.php. But some css changes would be needed to make it fit, especially for smaller screens. You could use flexbox to make everything fit.

Glad you like the theme, hope that is a little bit helpful.
