### ISSUE TITLE
No section editing possible

### ISSUE THREAD

**Issue by Josef-zos** [axlevxa/typowiki#11]
Section editing is not possible in typowiki. If I change to dokuwiki it is there. It would be a fine feature.

**Comment by priestdo** [comment]
I love this template but also need section editing.
Any chance this can be added?
If it were working, the admin user could always set it to 0 to disable it and get the current behavior, but for those of us with large pages it really is needed.

**Comment by axlevxa** [comment]
Hi, the new version supports section editing. Thanks for your feedback.

**Comment by priestdo** [comment]
Thanks! I look forward to returning to this template.
Greg

-
Greg Priest-Dorman
