### ISSUE TITLE
Would it be possible to adjust page width outside of template style settings?

### ISSUE THREAD

**Issue by tbwikiaccnt** [axlevxa/typowiki#15]
Hello, love this theme it looks awesome! I did see on the dokuwiki page that there is a known issue for not recognizing variables changed in the template setting page... is there an easy way to manually adjust the width in one of the css files? I must admit I am not experienced with website design or css and have been unable to adjust the page width on my own.

**Comment by axlevxa** [comment]
Hi there, unfortunately I cannot provide this kind of personal support for the template.
