### ISSUE TITLE
...and how can i change the background color on the main body?

### ISSUE THREAD

**Issue by karzinogen** [axlevxa/typowiki#9]
I had removed the underscores at the variable __background__     = "#fff" but it had no change

**Comment by axlevxa** [comment]
Hi, it's a [known issue](https://www.dokuwiki.org/template:typowiki#known_issues) that changing those variables doesn't work. I invite somebody to fix it but I can't.

If you want to change the background color, I suggest following these instructions:

Create a new file in the **css** folder called `custom.css`. Put the following (replace hex value with your color):
```
body {
    background-color: #2b970c  !important;
}
```

Edit the file called `style.ini`. In the list titled `[stylesheets]`, add the following at the end (line 38):

```
css/custom.css
```
Next time you go to your DokuWiki admin panel and click the save changes button, your customizations should be included. Let me know how it goes!

If you ever need to update the theme, be sure to leave these 2 files intact.
